import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import localFont from "next/font/local";
import { Inter } from 'next/font/google'; // Importation de la police Inter
import "./globals.css";
import { ThemeProvider } from "@emotion/react";
import darkTheme from "./dark.theme";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const inter = Inter({
  subsets: ['latin'], // Utilise le sous-ensemble 'latin' pour la police
  weight: ['400', '600'],
  style: 'italic',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//Route qui englobe tous les autres composants
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
      </body>
    </html>
  );
}